version: "3.2"
services:
  db:
    network_mode: "bridge"
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
          
  hasura:
    image: hasura/graphql-engine:latest
    network_mode: "bridge"
    restart: always
    ports: 
      - "9080:8080"
    links: 
      - db
    depends_on:
      - "db"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_ADMIN_SECRET_KEY}"
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "${HASURA_GRAPHQL_JWT_ALGO}","key": "${HASURA_GRAPHQL_JWT_SECRET_KEY}","claims_namespace": "${HASURA_JWT_NAMESPACE}","claims_format": "json","issuer": "${HOST}"}'
      VIRTUAL_HOST: "api.${HOST}"
      LETSENCRYPT_HOST: "api.${HOST}"
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}    
    
    
volumes:
  db-data:
