version: "3.2"
services:
  db:
    network_mode: "bridge"
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
          
  hasura:
    image: hasura/graphql-engine:v1.3.2
    network_mode: "bridge"
    restart: always
    ports: 
      - "8080"
    links: 
      - db
    depends_on:
      - "db"
    env_file:
      - .env
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://admin:${POSTGRES_PASSWORD}@db/postgres"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_ADMIN_SECRET_KEY}"
      HASURA_GRAPHQL_JWT_SECRET: "${HASURA_GRAPHQL_JWT_SECRET}"
      VIRTUAL_HOST: "api.${HOST}"
      LETSENCRYPT_HOST: "api.${HOST}"
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}
    
  pgadmin:
    network_mode: "bridge"
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: "80"
      VIRTUAL_HOST: db.${HOST}
      LETSENCRYPT_HOST: db.${HOST}
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}
    ports:
      - "9080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

volumes:
  db-data:
  pgadmin-data: